// GENERATED FILE — do not edit. Produced by parser-gen/codegen.py.
package prev26lsp.parser;

// The shared grammar alphabet: produced by the lexer, consumed by the
// parser and the tree. Declaration order == ordinal(), so ordinals match
// the parse-table indices.
public enum Symbol {
    // === NON-TERMINALS ===
    ADD_EXPR,
    ADD_EXPR_PRIME,
    ASSIGN_EXPR,
    ASSIGN_EXPR_PRIME,
    BOOL_EXPR,
    CAST_EXPR,
    CAST_EXPR_PRIME,
    COMPARISON,
    COMPARISON_PRIME,
    DEFINITION,
    DEFINITIONS,
    DEFINITIONS_PRIME,
    EEXPRS,
    ELSE_PART,
    EPARAMS,
    ETYPES,
    EXPR,
    EXPRS,
    EXPRS_PRIME,
    FIELD,
    FIELDS,
    FIELDS_PRIME,
    FUN_BODY,
    FUN_DEF,
    INT_PFX_EXPR,
    LET_DEFINITIONS,
    LET_DEFINITIONS_PRIME,
    LOGICAL_AND,
    LOGICAL_AND_PRIME,
    LOGICAL_OR,
    LOGICAL_OR_PRIME,
    MUL_EXPR,
    MUL_EXPR_PRIME,
    PARAM,
    PARAMS,
    PARAMS_PRIME,
    PFIELDS,
    PFIELDS_PRIME,
    PFX_EXPR,
    POSTFIX_EXPR,
    POSTFIX_EXPR_PRIME,
    PRIMARY_EXPR,
    PROGRAM,
    PTR_EXPR,
    TYPE,
    TYPE_DEF,
    TYPE_NON_ID,
    TYPE_PAREN,
    TYPE_PAREN_ID,
    TYPES,
    TYPES_PRIME,
    VAR_DEF,
    VOID_EXPR,

    // === TERMINALS ===
    AND,
    AS,
    ASSIGN,
    BOOL,
    CARET,
    CHAR,
    CHARCONST,
    COLON,
    COMMA,
    DO,
    DOT,
    ELSE,
    END,
    EOF,
    EQU,
    FALSE,
    FUN,
    GEQ,
    GT,
    ID,
    IF,
    IN,
    INT,
    INTCONST,
    LCURLY,
    LEQ,
    LET,
    LPAREN,
    LSQUARE,
    LT,
    MINUS,
    NEQ,
    NIL,
    NONE,
    NOT,
    OR,
    PERCENT,
    PLUS,
    RCURLY,
    RPAREN,
    RSQUARE,
    SIZEOF,
    SLASH,
    STAR,
    STRINGCONST,
    THEN,
    TRUE,
    TYP,
    VAR,
    VOID,
    WHILE;

    public static final Symbol START_SYMBOL = Symbol.PROGRAM;

    public static final int NONTERMINAL_COUNT = 53;

    /** A symbol is a terminal iff its ordinal is at/after the terminals block. */
    public boolean isTerminal() {
        return ordinal() >= NONTERMINAL_COUNT;
    }
}
